#!/usr/bin/env bash
# script that configures a new Ubuntu machine respecting certain requirements
# (script will be run on the server itself)

# requirements:
# 	Install nginx on your web-01 server

#	Nginx should be listening on port 80

#	When querying Nginx at its root / with a GET request (requesting a page)
#	using curl, it must return a page that contains the string "Hello World!"

# update packet list
sudo apt update

# install nginx
sudo apt install -y nginx

# configure server to listen on port 80
echo "server {
	listen       80;
	server_name  localhost;

	location  /  {
		root     /var/www/html;
		index    index.html;
	}
}"  |  sudo tee /etc/nginx/sites-available/default

# create a html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# restart Nginx server
sudo /etc/init.d/nginx restart

