#!/usr/bin/env bash
# script that transfers a file from our client to a server

# should accept 4 parameters
# Strict host key checking is disabled when using scp
# prevents the addition of the remote host to the known_hosts file

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$1" "$3"@"$2":~/
fi

