#!/usr/bin/env bash
# script:
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself when
#+ receiving a SIGQUIT or SIGTERM signal

sudo bash -c "echo $$ > /var/run/myscript.pid"

function sig_term {
    echo "I hate the kill command"
    sudo rm -f /var/run/myscript.pid
    exit
}

function sig_int {
    echo "Y U no love me?!"
    exit
}

function sig_quit {
    sudo rm -f /var/run/myscript.pid
    exit
}

trap sig_term SIGTERM
trap sig_int SIGINT
trap sig_quit SIGQUIT

while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
