#!/usr/bin/env bash
# script displays the content of the file /etc/passwd.
#+ Your script should only display:
#+ username
#+ user id
#+ Home directory path for the user

while IFS=":" read -ra line; do
    echo "${line[0]}:${line[3]}:${line[5]}"
done < /etc/passwd
