#!/usr/bin/env bash
# script displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

min=1
hr=0
while ((hr < 13)); do
    echo "Hour: $hr";
    while ((min < 60)); do
        echo "$min";
        ((min++));
    done
    min=1;
    ((hr++));
done


