#!/usr/bin/env bash

sudo apt update

sudo apt install -y ufw

# Allow outgoing and Deny incoming traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# Enable ufw
sudo ufw enable

# check status of ufw and configuration
sudo ufw status verbose

