#!/usr/bin/env bash
# script resolves localhost to 127.0.0.2
# script resolves facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/etc/hosts
sed -i "\$a 8.8.8.8 facebook.com" ~/etc/hosts
cp -f ~/hosts.new /etc/hosts

